services:
  postgres:
    image: ${postgres-image}
    container_name: ${artifactId}_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    networks:
      - application-network

  adminer:
    image: adminer:5.2.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - application-network

  postgres-keycloak:
    image: ${postgres-image}
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
    networks:
      - application-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    command: "start-dev"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9999
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "9999:8080"
    depends_on:
      - postgres-keycloak
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - application-network

volumes:
  postgres_vol:
    driver: local
  postgres_keycloak_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  application-network:
    driver: bridge
